[general]
import = [
    "~/.config/alacritty/theme/catppuccin-macchiato.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
blur = true
opacity = 0.66
padding = { x = 5, y = 5 }

[font]
size = 14

[terminal]
shell.program = "/opt/homebrew/bin/tmux"
shell.args = ["new-session", "-A", "-D", "-s", "main"]